# Generated by Django 3.2.5 on 2021-07-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='enter category', max_length=20, null=True, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter menu item name', max_length=30, verbose_name='menu item name')),
                ('discount', models.IntegerField(blank=True, default=0, help_text='enter item discount(%)', null=True, verbose_name='discount')),
                ('price', models.FloatField(help_text='enter item price', verbose_name='price')),
                ('image', models.FileField(blank=True, help_text='upload image of item', null=True, upload_to='cafe5/menu_items/images/', verbose_name='item image')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, help_text='time of creation of item', verbose_name='time of adding item')),
                ('modify_timestamp', models.DateTimeField(auto_now=True, help_text='time of modify of item', verbose_name='time of update item')),
                ('category_id', models.ForeignKey(help_text='define category', on_delete=django.db.models.deletion.CASCADE, to='landing.category', verbose_name='menu item category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='enter order number', max_length=5, verbose_name='order number')),
                ('status', models.CharField(choices=[('NW', 'new'), ('PR', 'preparing'), ('DV', 'delivered'), ('PO', 'pay off')], default='new', help_text='specify state of order', max_length=30, verbose_name='status')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, help_text='specify time of adding order', verbose_name='time of adding order')),
                ('menu_item_number', models.IntegerField(default=1, help_text='enter number of item that you want', verbose_name='number of item')),
                ('menu_item_id', models.ForeignKey(help_text='specify menu item in order', on_delete=django.db.models.deletion.CASCADE, to='landing.menuitem', verbose_name='menu item id')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(help_text='enter table number', max_length=3, verbose_name='table number')),
                ('cafe_space_position', models.CharField(choices=[('NE', 'north-east'), ('NW', 'north-west'), ('ME', 'mid-east'), ('MW', 'mid-west'), ('SE', 'south-east'), ('SW', 'south-west')], help_text='table position in cafe', max_length=25, verbose_name='position in cafe')),
                ('table_status', models.CharField(choices=[('FR', 'free'), ('FL', 'full'), ('RS', 'reserve')], default='free', help_text='specify status of table', max_length=25, verbose_name='table status')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, help_text='specify time of export bill', verbose_name='time of export bill')),
                ('order_id', models.ForeignKey(help_text='specify order', on_delete=django.db.models.deletion.CASCADE, to='landing.order', verbose_name='order id')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(help_text='specify table for order', on_delete=django.db.models.deletion.CASCADE, to='landing.table', verbose_name='table id'),
        ),
    ]
