# Generated by Django 3.2.5 on 2021-07-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='category', help_text='enter category', max_length=20, null=True, verbose_name='english category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(blank=True, default='نوع دسته غذا و نوشیدنی', help_text='enter category', max_length=20, null=True, verbose_name='farsi category'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(default='menu', help_text='enter menu item name', max_length=30, verbose_name='menu item name in english'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_fa',
            field=models.CharField(default='منو', help_text='enter menu item name', max_length=30, verbose_name='menu item name in farsi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(help_text='specify table for order', on_delete=django.db.models.deletion.CASCADE, to='landing.table', verbose_name='table'),
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='order_id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='order_id',
            field=models.ManyToManyField(help_text='specify order', to='landing.Order', verbose_name='order'),
        ),
    ]
