# Generated by Django 3.2.5 on 2021-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_remove_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='enter your name', max_length=50, verbose_name='customer name')),
                ('email', models.CharField(help_text='enter your email', max_length=50, verbose_name='email')),
                ('message_text', models.CharField(help_text='enter your message', max_length=250, verbose_name='message text')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, help_text='enter category', max_length=20, null=True, verbose_name='english category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fa',
            field=models.CharField(blank=True, help_text='enter category', max_length=20, null=True, verbose_name='farsi category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, help_text='upload image of item', null=True, upload_to='media/landing/menu_items/images/', verbose_name='item image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(help_text='enter menu item name', max_length=30, verbose_name='menu item name in english'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name_fa',
            field=models.CharField(help_text='enter menu item name', max_length=30, verbose_name='menu item name in farsi'),
        ),
    ]
